services:
  db:
    image: postgres:14.4
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bdd_cuenta_movimiento
    container_name: cuenta_movimiento
    volumes:
      - ./postgres:/var/lib/postgresql/data